# Jekyll configuration
title: check-spelling action
description: check-spelling GitHub action
theme: jekyll-theme-slate
url: "https://www.check-spelling.dev"
markdown: GFM
twitter_username: _check_spelling
favicon: favicon.ico
